-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               8.0.30 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.17.0.7270
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Dumping structure for table siskadb.attmast
CREATE TABLE IF NOT EXISTS `attmast` (
  `ATT_MAST_CODE` char(8) NOT NULL,
  `ATT_MAST_ROOM` char(2) DEFAULT NULL,
  `ATT_MAST_PAYM` char(1) DEFAULT NULL,
  `ATT_MAST_USER` char(5) DEFAULT NULL,
  `ATT_MAST_RATE` char(1) DEFAULT NULL,
  `ATT_NOMI_AMNT` decimal(15,2) DEFAULT NULL,
  `ATT_VIEW_STAT` char(1) DEFAULT NULL,
  `ATT_ENTR_DATE` date DEFAULT NULL,
  `ATT_ENTR_TIME` time DEFAULT NULL,
  `ATT_ENTR_USER` char(5) DEFAULT NULL,
  `ATT_UPDT_DATE` date DEFAULT NULL,
  `ATT_UPDT_TIME` time DEFAULT NULL,
  `ATT_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`ATT_MAST_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.autojrnl
CREATE TABLE IF NOT EXISTS `autojrnl` (
  `TRXA_SALE_CODE` char(14) DEFAULT NULL,
  `TRXA_REGI_CODE` char(14) DEFAULT NULL,
  `TRXA_COAC_CODE` char(13) DEFAULT NULL,
  `TRXA_JRNL_DATE` date DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.coacmast
CREATE TABLE IF NOT EXISTS `coacmast` (
  `COAC_MAST_CODE` char(13) DEFAULT NULL,
  `COAC_MAST_PRNT` char(3) DEFAULT NULL,
  `COAC_MAST_NAME` varchar(100) DEFAULT NULL,
  `COAC_MAST_COSG` char(1) DEFAULT NULL,
  `COAC_MAST_STAT` char(1) DEFAULT NULL,
  `COAC_NORM_BLNC` char(2) DEFAULT NULL,
  `COAC_FNRP_STAT` char(2) DEFAULT NULL,
  `COAC_MAST_NOTE` varchar(100) DEFAULT NULL,
  `COAC_VIEW_STAT` char(1) DEFAULT NULL,
  `COAC_ENTR_DATE` date DEFAULT NULL,
  `COAC_ENTR_TIME` time DEFAULT NULL,
  `COAC_ENTR_USER` varchar(5) DEFAULT NULL,
  `COAC_UPDT_DATE` date DEFAULT NULL,
  `COAC_UPDT_TIME` time DEFAULT NULL,
  `COAC_UPDT_USER` varchar(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.custmast
CREATE TABLE IF NOT EXISTS `custmast` (
  `CUST_MAST_CODE` char(7) NOT NULL,
  `CUST_MAIN_NAME` varchar(50) DEFAULT NULL,
  `CUST_MAIN_TYPE` char(1) DEFAULT NULL,
  `CUST_MAIN_ADDR` varchar(100) DEFAULT NULL,
  `CUST_MAIN_CITY` varchar(10) DEFAULT NULL,
  `CUST_MAIN_CTRY` varchar(10) DEFAULT NULL,
  `CUST_MAIN_PHNE` varchar(18) DEFAULT NULL,
  `CUST_CRDT_LIMT` decimal(15,2) DEFAULT NULL,
  `CUST_SHIP_NAME` varchar(50) DEFAULT NULL,
  `CUST_SHIP_ADDR` varchar(50) DEFAULT NULL,
  `CUST_VIEW_STAT` char(1) DEFAULT NULL,
  `CUST_ENTR_DATE` date DEFAULT NULL,
  `CUST_ENTR_TIME` time DEFAULT NULL,
  `CUST_ENTR_USER` char(5) DEFAULT NULL,
  `CUST_UPDT_DATE` date DEFAULT NULL,
  `CUST_UPDT_TIME` time DEFAULT NULL,
  `CUST_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`CUST_MAST_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.diagmast
CREATE TABLE IF NOT EXISTS `diagmast` (
  `DIAG_ICD_CATEGORY` varchar(200) DEFAULT NULL,
  `DIAG_ICD_SUBCATE` varchar(200) DEFAULT NULL,
  `DIAG_ICD_CODE` varchar(6) DEFAULT NULL,
  `DIAG_ICD_NOTE` varchar(200) DEFAULT NULL,
  `DIAG_VIEW_STAT` char(1) DEFAULT NULL,
  `DIAG_ENTR_DATE` date DEFAULT NULL,
  `DIAG_ENTR_TIME` time DEFAULT NULL,
  `DIAG_ENTR_USER` char(5) DEFAULT NULL,
  `DIAG_UPDT_DATE` date DEFAULT NULL,
  `DIAG_UPDT_TIME` time DEFAULT NULL,
  `DIAG_UPDT_USER` char(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.emplmast
CREATE TABLE IF NOT EXISTS `emplmast` (
  `EMPL_MAST_CODE` char(7) NOT NULL,
  `EMPL_FRST_NAME` varchar(30) DEFAULT NULL,
  `EMPL_LAST_NAME` varchar(20) DEFAULT NULL,
  `EMPL_MAIN_GEND` char(1) DEFAULT NULL,
  `EMPL_MAIN_BIRT` date DEFAULT NULL,
  `EMPL_MAIN_BLOD` varchar(2) DEFAULT NULL,
  `EMPL_FNGR_CODE` int DEFAULT NULL,
  `EMPL_MAIN_TIDN` char(20) DEFAULT NULL,
  `EMPL_MAIN_STAT` varchar(3) DEFAULT NULL,
  `EMPL_MKTP_ADDR` varchar(100) DEFAULT NULL,
  `EMPL_MKTP_CITY` varchar(20) DEFAULT NULL,
  `EMPL_MKTP_PROV` varchar(20) DEFAULT NULL,
  `EMPL_MKTP_CTRY` varchar(10) DEFAULT NULL,
  `EMPL_MAIN_HP01` varchar(18) DEFAULT NULL,
  `EMPL_MAIN_HP02` varchar(18) DEFAULT NULL,
  `EMPL_MAIN_MAIL` varchar(30) DEFAULT NULL,
  `EMPL_HIGH_EDUC` varchar(4) DEFAULT NULL,
  `EMPL_LAST_SCHL` varchar(50) DEFAULT NULL,
  `EMPL_DOCU_STAT` char(1) DEFAULT NULL,
  `EMPL_MAIN_HOBI` varchar(50) DEFAULT NULL,
  `EMPL_HIRE_DATE` date DEFAULT NULL,
  `EMPL_ACTI_DATE` date DEFAULT NULL,
  `EMPL_MAIN_DIVI` char(3) DEFAULT NULL,
  `EMPL_MAIN_PSTN` char(3) DEFAULT NULL,
  `EMPL_RSGN_DATE` date DEFAULT NULL,
  `EMPL_RSGN_NOTE` varchar(50) DEFAULT NULL,
  `EMPL_MAIN_PICT` text,
  `EMPL_BANK_CODE` char(3) DEFAULT NULL,
  `EMPL_BANK_ACCT` varchar(20) DEFAULT NULL,
  `EMPL_BANK_PERS` varchar(50) DEFAULT NULL,
  `EMPL_VIEW_STAT` char(1) DEFAULT NULL,
  `EMPL_ENTR_DATE` date DEFAULT NULL,
  `EMPL_ENTR_TIME` time DEFAULT NULL,
  `EMPL_ENTR_USER` char(5) DEFAULT NULL,
  `EMPL_UPDT_DATE` date DEFAULT NULL,
  `EMPL_UPDT_TIME` time DEFAULT NULL,
  `EMPL_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`EMPL_MAST_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.feemast
CREATE TABLE IF NOT EXISTS `feemast` (
  `FEE_MAST_CODE` char(8) NOT NULL,
  `FEE_MAST_ROOM` char(2) DEFAULT NULL,
  `FEE_MAST_TYPE` char(1) DEFAULT NULL,
  `FEE_MAST_PAYM` char(1) DEFAULT NULL,
  `FEE_MAST_USER` char(5) DEFAULT NULL,
  `FEE_MEDI_CODE` char(8) DEFAULT NULL,
  `FEE_MAST_RATE` char(1) DEFAULT NULL,
  `FEE_PART_USER` decimal(15,2) DEFAULT NULL,
  `FEE_PART_HOME` decimal(15,2) DEFAULT NULL,
  `FEE_MAXI_AMNT` decimal(15,2) DEFAULT NULL,
  `FEE_MINI_AMNT` decimal(15,2) DEFAULT NULL,
  `FEE_VIEW_STAT` char(1) DEFAULT NULL,
  `FEE_ENTR_DATE` date DEFAULT NULL,
  `FEE_ENTR_TIME` time DEFAULT NULL,
  `FEE_ENTR_USER` char(5) DEFAULT NULL,
  `FEE_UPDT_DATE` date DEFAULT NULL,
  `FEE_UPDT_TIME` time DEFAULT NULL,
  `FEE_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`FEE_MAST_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.fixeloca
CREATE TABLE IF NOT EXISTS `fixeloca` (
  `FIXE_LOCA_CODE` char(3) NOT NULL,
  `FIXE_LOCA_NAME` varchar(50) DEFAULT NULL,
  `FIXE_LOCA_ADDR` varchar(100) DEFAULT NULL,
  `FIXE_EMPL_CODE` char(10) DEFAULT NULL,
  `FIXE_LOCA_NOTE` varchar(100) DEFAULT NULL,
  `FIXE_VIEW_STAT` char(1) DEFAULT NULL,
  `FIXE_ENTR_DATE` date DEFAULT NULL,
  `FIXE_ENTR_TIME` time DEFAULT NULL,
  `FIXE_ENTR_USER` varchar(5) DEFAULT NULL,
  `FIXE_UPDT_DATE` date DEFAULT NULL,
  `FIXE_UPDT_TIME` time DEFAULT NULL,
  `FIXE_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`FIXE_LOCA_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.invemast
CREATE TABLE IF NOT EXISTS `invemast` (
  `INVE_MAST_CODE` char(4) NOT NULL,
  `INVE_MAIN_TYPE` char(4) DEFAULT NULL,
  `INVE_MAIN_UNIT` char(3) DEFAULT NULL,
  `INVE_SALE_UNIT` char(3) DEFAULT NULL,
  `INVE_MAIN_SPEC` char(2) DEFAULT NULL,
  `INVE_MAIN_VARN` char(2) DEFAULT NULL,
  `INVE_WITH_SRNM` char(1) DEFAULT NULL,
  `INVE_PART_TYPE` char(2) DEFAULT NULL,
  `INVE_COST_FRGT` char(1) DEFAULT NULL,
  `INVE_PART_NAME` varchar(50) DEFAULT NULL,
  `INVE_PART_ALAS` varchar(50) DEFAULT NULL,
  `INVE_DEFA_WARE` char(4) DEFAULT NULL,
  `INVE_STOCK_MINI` int DEFAULT NULL,
  `INVE_MAIN_NOTE` varchar(100) DEFAULT NULL,
  `INVE_MAIN_PRIC` char(1) DEFAULT NULL,
  `INVE_GRTE_TYPE` char(1) DEFAULT NULL,
  `INVE_GRTE_LIMT` int DEFAULT NULL,
  `INVE_EXCE_RCVE` int DEFAULT NULL,
  `INVE_LACK_RCVE` int DEFAULT NULL,
  `INVE_VIEW_STAT` char(1) DEFAULT NULL,
  `INVE_ENTR_DATE` date DEFAULT NULL,
  `INVE_ENTR_TIME` time DEFAULT NULL,
  `INVE_ENTR_USER` char(5) DEFAULT NULL,
  `INVE_UPDT_DATE` date DEFAULT NULL,
  `INVE_UPDT_TIME` time DEFAULT NULL,
  `INVE_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`INVE_MAST_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.investock
CREATE TABLE IF NOT EXISTS `investock` (
  `INVE_STOCK_CODE` char(4) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `INVE_PROC_CODE` char(7) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `INVE_STOCK_TYPE` char(4) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `INVE_STOCK_BTCH` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `INVE_STOCK_SRNM` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `INVE_STOCK_NAME` varchar(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `INVE_WARE_CODE` char(4) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `INVE_STOCK_PRIC` decimal(15,2) DEFAULT NULL,
  `INVE_STOCK_QUTY` int DEFAULT NULL,
  `INVE_EXPR_DATE` date DEFAULT NULL,
  `INVE_VIEW_STAT` char(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `INVE_ENTR_DATE` date DEFAULT NULL,
  `INVE_ENTR_TIME` time DEFAULT NULL,
  `INVE_ENTR_USER` char(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `INVE_UPDT_DATE` date DEFAULT NULL,
  `INVE_UPDT_TIME` time DEFAULT NULL,
  `INVE_UPDT_USER` char(5) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.itemdrug
CREATE TABLE IF NOT EXISTS `itemdrug` (
  `ITEM_DRUG_CODE` char(14) DEFAULT NULL,
  `ITEM_STOCK_CODE` char(4) DEFAULT NULL,
  `ITEM_STOCK_BTCH` varchar(10) DEFAULT NULL,
  `ITEM_DRUG_CONC` char(1) DEFAULT NULL,
  `ITEM_STOCK_PRIC` decimal(15,2) DEFAULT NULL,
  `ITEM_STOCK_QUTY` int DEFAULT NULL,
  `ITEM_DRUG_SGNA` char(2) DEFAULT NULL,
  `ITEM_DRUG_USAG` varchar(50) DEFAULT NULL,
  `ITEM_DRUG_STAT` char(1) DEFAULT NULL,
  `ITEM_VIEW_STAT` char(1) DEFAULT NULL,
  `ITEM_ENTR_DATE` date DEFAULT NULL,
  `ITEM_ENTR_TIME` time DEFAULT NULL,
  `ITEM_ENTR_USER` char(5) DEFAULT NULL,
  `ITEM_UPDT_DATE` date DEFAULT NULL,
  `ITEM_UPDT_TIME` time DEFAULT NULL,
  `ITEM_UPDT_USER` char(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.itemexec
CREATE TABLE IF NOT EXISTS `itemexec` (
  `ITEM_EXEC_CODE` char(7) DEFAULT NULL,
  `ITEM_STOCK_CODE` char(4) DEFAULT NULL,
  `ITEM_STOCK_NAME` varchar(50) DEFAULT NULL,
  `ITEM_STOCK_QUTY` int DEFAULT NULL,
  `ITEM_PART_UNIT` char(3) DEFAULT NULL,
  `ITEM_STOCK_SRNM` varchar(10) DEFAULT NULL,
  `ITEM_STOCK_BTCH` varchar(10) DEFAULT NULL,
  `ITEM_CART_CODE` varchar(10) DEFAULT NULL,
  `ITEM_DIMM_CODE` varchar(10) DEFAULT NULL,
  `ITEM_STOCK_NOTE` varchar(100) DEFAULT NULL,
  `ITEM_VIEW_STAT` char(1) DEFAULT NULL,
  `ITEM_ENTR_DATE` date DEFAULT NULL,
  `ITEM_ENTR_TIME` time DEFAULT NULL,
  `ITEM_ENTR_USER` char(5) DEFAULT NULL,
  `ITEM_UPDT_DATE` date DEFAULT NULL,
  `ITEM_UPDT_TIME` time DEFAULT NULL,
  `ITEM_UPDT_USER` char(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.itemopna
CREATE TABLE IF NOT EXISTS `itemopna` (
  `ITEM_OPNA_CODE` char(7) DEFAULT NULL,
  `ITEM_WARE_CODE` char(4) DEFAULT NULL,
  `ITEM_STOCK_CODE` char(4) DEFAULT NULL,
  `ITEM_STOCK_NAME` varchar(50) DEFAULT NULL,
  `ITEM_STOCK_QUTY` int DEFAULT NULL,
  `ITEM_PART_UNIT` char(3) DEFAULT NULL,
  `ITEM_STOCK_SRNM` varchar(10) DEFAULT NULL,
  `ITEM_STOCK_BTCH` varchar(10) DEFAULT NULL,
  `ITEM_STOCK_OPNA` int DEFAULT NULL,
  `ITEM_VIEW_STAT` char(1) DEFAULT NULL,
  `ITEM_ENTR_DATE` date DEFAULT NULL,
  `ITEM_ENTR_TIME` time DEFAULT NULL,
  `ITEM_ENTR_USER` char(5) DEFAULT NULL,
  `ITEM_UPDT_DATE` date DEFAULT NULL,
  `ITEM_UPDT_TIME` time DEFAULT NULL,
  `ITEM_UPDT_USER` char(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.itemproc
CREATE TABLE IF NOT EXISTS `itemproc` (
  `ITEM_PROC_CODE` char(7) DEFAULT NULL,
  `ITEM_PART_CODE` char(4) DEFAULT NULL,
  `ITEM_PART_UNIT` char(3) DEFAULT NULL,
  `ITEM_QUTY_ORDR` int DEFAULT NULL,
  `ITEM_QUTY_RCVE` int DEFAULT NULL,
  `ITEM_PART_PRIC` decimal(15,2) DEFAULT NULL,
  `ITEM_PROC_BTCH` varchar(10) DEFAULT NULL,
  `ITEM_PROC_SRNM` varchar(10) DEFAULT NULL,
  `ITEM_CHRG_VALU` int DEFAULT NULL,
  `ITEM_CHRG_MTHD` char(1) DEFAULT NULL,
  `ITEM_ARRV_REQU` date DEFAULT NULL,
  `ITEM_WARE_CODE` char(4) DEFAULT NULL,
  `ITEM_EMPL_CODE` char(10) DEFAULT NULL,
  `ITEM_VIEW_STAT` char(1) DEFAULT NULL,
  `ITEM_ENTR_DATE` date DEFAULT NULL,
  `ITEM_ENTR_TIME` time DEFAULT NULL,
  `ITEM_ENTR_USER` varchar(5) DEFAULT NULL,
  `ITEM_UPDT_DATE` date DEFAULT NULL,
  `ITEM_UPDT_TIME` time DEFAULT NULL,
  `ITEM_UPDT_USER` varchar(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.itemvend
CREATE TABLE IF NOT EXISTS `itemvend` (
  `ITEM_VEND_CODE` char(7) DEFAULT NULL,
  `ITEM_INVC_CODE` varchar(20) DEFAULT NULL,
  `ITEM_DUED_DATE` date DEFAULT NULL,
  `ITEM_COAC_CODE` char(13) DEFAULT NULL,
  `ITEM_CHEQ_CODE` varchar(10) DEFAULT NULL,
  `ITEM_CHEQ_DATE` date DEFAULT NULL,
  `ITEM_CHEQ_BANK` char(3) DEFAULT NULL,
  `ITEM_SUMM_AMNT` decimal(15,2) DEFAULT NULL,
  `ITEM_PAYM_AMNT` decimal(15,2) DEFAULT NULL,
  `ITEM_VIEW_STAT` char(1) DEFAULT NULL,
  `ITEM_ENTR_DATE` date DEFAULT NULL,
  `ITEM_ENTR_TIME` time DEFAULT NULL,
  `ITEM_ENTR_USER` char(5) DEFAULT NULL,
  `ITEM_UPDT_DATE` date DEFAULT NULL,
  `ITEM_UPDT_TIME` time DEFAULT NULL,
  `ITEM_UPDT_USER` char(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.labomast
CREATE TABLE IF NOT EXISTS `labomast` (
  `LABO_MAST_CODE` char(7) NOT NULL,
  `LABO_SUBS_CODE` char(2) DEFAULT NULL,
  `LABO_SIZE_CODE` char(8) DEFAULT NULL,
  `LABO_SIZE_NAME` varchar(50) DEFAULT NULL,
  `LABO_UNIT_NAME` varchar(10) DEFAULT NULL,
  `LABO_VALU_MIN` varchar(10) DEFAULT NULL,
  `LABO_VALU_MAX` varchar(10) DEFAULT NULL,
  `LABO_VALU_STRG` varchar(20) DEFAULT NULL,
  `LABO_PATI_GEND` char(1) DEFAULT NULL,
  `LABO_VIEW_STAT` char(1) DEFAULT NULL,
  `LABO_ENTR_DATE` date DEFAULT NULL,
  `LABO_ENTR_TIME` time DEFAULT NULL,
  `LABO_ENTR_USER` varchar(5) DEFAULT NULL,
  `LABO_UPDT_DATE` date DEFAULT NULL,
  `LABO_UPDT_TIME` time DEFAULT NULL,
  `LABO_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`LABO_MAST_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.passiden
CREATE TABLE IF NOT EXISTS `passiden` (
  `PASS_USER_IDEN` char(5) NOT NULL,
  `PASS_EMPL_CODE` varchar(10) DEFAULT NULL,
  `PASS_USER_NAME` varchar(50) DEFAULT NULL,
  `PASS_USER_PSWD` text,
  `PASS_USER_TYPE` char(1) DEFAULT NULL,
  `PASS_IDEN_NEW` char(1) DEFAULT NULL,
  `PASS_IDEN_PREV` char(1) DEFAULT NULL,
  `PASS_IDEN_DELL` char(1) DEFAULT NULL,
  `PASS_IDEN_VIEW` char(1) DEFAULT NULL,
  `PASS_TRXA_ENTR` char(1) DEFAULT NULL,
  `PASS_COAC_ENTR` char(1) DEFAULT NULL,
  `PASS_TBLA_ENTR` char(1) DEFAULT NULL,
  `PASS_DIVI_ENTR` char(1) DEFAULT NULL,
  `PASS_REPO_VIEW` char(1) DEFAULT NULL,
  `PASS_SPEC_ITEM` char(1) DEFAULT NULL,
  `PASS_INVE_ENTR` char(1) DEFAULT NULL,
  `PASS_WARE_HOUS` char(1) DEFAULT NULL,
  `PASS_TRANS_REQU` char(1) DEFAULT NULL,
  `PASS_TRANS_APRO` char(1) DEFAULT NULL,
  `PASS_TRANS_EXEC` char(1) DEFAULT NULL,
  `PASS_TRANS_RECE` char(1) DEFAULT NULL,
  `PASS_STOCK_OPNA` char(1) DEFAULT NULL,
  `PASS_STOCK_ADJU` char(1) DEFAULT NULL,
  `PASS_STOCK_EXEC` char(1) DEFAULT NULL,
  `PASS_STOCK_REPO` char(1) DEFAULT NULL,
  `PASS_SUPL_ENTR` char(1) DEFAULT NULL,
  `PASS_PROC_ENTR` char(1) DEFAULT NULL,
  `PASS_PROC_UPDT` char(1) DEFAULT NULL,
  `PASS_PROC_INVC` char(1) DEFAULT NULL,
  `PASS_REGI_ENTR` char(1) DEFAULT NULL,
  `PASS_TRXA_POLI` char(1) DEFAULT NULL,
  `PASS_MEDI_ENTR` char(1) DEFAULT NULL,
  `PASS_LABO_ENTR` char(1) DEFAULT NULL,
  `PASS_CUST_ENTR` char(1) DEFAULT NULL,
  `PASS_SALE_ENTR` char(1) DEFAULT NULL,
  `PASS_SALE_VIEW` char(1) DEFAULT NULL,
  `PASS_DRUG_ENTR` char(1) DEFAULT NULL,
  `PASS_DRUG_VIEW` char(1) DEFAULT NULL,
  `PASS_MEDI_REPO` char(1) DEFAULT NULL,
  `PASS_VEND_ENTR` char(1) DEFAULT NULL,
  `PASS_VEND_UPDT` char(1) DEFAULT NULL,
  `PASS_VEND_EXEC` char(1) DEFAULT NULL,
  `PASS_CUST_RCVD` char(1) DEFAULT NULL,
  `PASS_PAYM_CASH` char(1) DEFAULT NULL,
  `PASS_DEBT_ENTR` char(1) DEFAULT NULL,
  `PASS_CRDT_ENTR` char(1) DEFAULT NULL,
  `PASS_BANK_RECO` char(1) DEFAULT NULL,
  `PASS_FIXE_ASSE` char(1) DEFAULT NULL,
  `PASS_EMPL_ENTR` char(1) DEFAULT NULL,
  `PASS_PAYR_ENTR` char(1) DEFAULT NULL,
  `PASS_ENTR_DATE` date DEFAULT NULL,
  `PASS_ENTR_TIME` time DEFAULT NULL,
  `PASS_ENTR_USER` char(5) DEFAULT NULL,
  `PASS_UPDT_DATE` date DEFAULT NULL,
  `PASS_UPDT_TIME` time DEFAULT NULL,
  `PASS_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`PASS_USER_IDEN`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.patimast
CREATE TABLE IF NOT EXISTS `patimast` (
  `PATI_MAST_CODE` char(10) NOT NULL,
  `PATI_MAIN_PIDN` char(16) DEFAULT NULL,
  `PATI_MAIN_TITL` char(3) DEFAULT NULL,
  `PATI_MAIN_NAME` varchar(50) DEFAULT NULL,
  `PATI_MAIN_GEND` char(1) DEFAULT NULL,
  `PATI_MAIN_BIRT` date DEFAULT NULL,
  `PATI_MAIN_BLOD` varchar(2) DEFAULT NULL,
  `PATI_MAIN_ADDR` varchar(100) DEFAULT NULL,
  `PATI_MAIN_WARD` varchar(50) DEFAULT NULL,
  `PATI_MAIN_DIST` varchar(50) DEFAULT NULL,
  `PATI_MAIN_CITY` varchar(50) DEFAULT NULL,
  `PATI_MAIN_PROV` varchar(50) DEFAULT NULL,
  `PATI_MAIN_RELI` varchar(50) DEFAULT NULL,
  `PATI_MAIN_CTZN` char(3) DEFAULT NULL,
  `PATI_MAIN_STAT` varchar(10) DEFAULT NULL,
  `PATI_MAIN_PROF` varchar(50) DEFAULT NULL,
  `PATI_MAIN_EDUC` varchar(10) DEFAULT NULL,
  `PATI_MAIN_PHNE` varchar(18) DEFAULT NULL,
  `PATI_MAIN_MAIL` varchar(50) DEFAULT NULL,
  `PATI_MAIN_PRNT` varchar(100) DEFAULT NULL,
  `PATI_VIEW_STAT` char(1) DEFAULT NULL,
  `PATI_ENTR_DATE` date DEFAULT NULL,
  `PATI_ENTR_TIME` time DEFAULT NULL,
  `PATI_ENTR_USER` char(5) DEFAULT NULL,
  `PATI_UPDT_DATE` date DEFAULT NULL,
  `PATI_UPDT_TIME` time DEFAULT NULL,
  `PATI_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`PATI_MAST_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.queue_calls
CREATE TABLE IF NOT EXISTS `queue_calls` (
  `id` int NOT NULL AUTO_INCREMENT,
  `channel` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `queue_no` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `patient_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `poli_name` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=17334 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.suplmast
CREATE TABLE IF NOT EXISTS `suplmast` (
  `SUPL_MAST_CODE` char(7) NOT NULL,
  `SUPL_MAIN_NAME` varchar(50) DEFAULT NULL,
  `SUPL_MAIN_ADDR` varchar(100) DEFAULT NULL,
  `SUPL_MAIN_CITY` varchar(10) DEFAULT NULL,
  `SUPL_MAIN_CTRY` varchar(10) DEFAULT NULL,
  `SUPL_MAIN_PHNE` varchar(18) DEFAULT NULL,
  `SUPL_MAIN_FAXI` varchar(18) DEFAULT NULL,
  `SUPL_MAIN_MAIL` varchar(30) DEFAULT NULL,
  `SUPL_MAIN_WEBS` varchar(50) DEFAULT NULL,
  `SUPL_MAIN_PERS` varchar(50) DEFAULT NULL,
  `SUPL_MAIN_TIDN` char(20) DEFAULT NULL,
  `SUPL_MAIN_TERM` int DEFAULT NULL,
  `SUPL_ESTI_ARRV` int DEFAULT NULL,
  `SUPL_ESTI_DELI` int DEFAULT NULL,
  `SUPL_PAYA_LIMT` decimal(15,2) DEFAULT NULL,
  `SUPL_BANK_CODE` char(3) DEFAULT NULL,
  `SUPL_AVAI_FRWD` char(1) DEFAULT NULL,
  `SUPL_VIEW_STAT` char(1) DEFAULT NULL,
  `SUPL_ENTR_DATE` date DEFAULT NULL,
  `SUPL_ENTR_TIME` time DEFAULT NULL,
  `SUPL_ENTR_USER` char(5) DEFAULT NULL,
  `SUPL_UPDT_DATE` date DEFAULT NULL,
  `SUPL_UPDT_TIME` time DEFAULT NULL,
  `SUPL_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`SUPL_MAST_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.tblacoac
CREATE TABLE IF NOT EXISTS `tblacoac` (
  `TBLA_COAC_CODE` char(3) NOT NULL,
  `TBLA_COAC_NAME` varchar(100) DEFAULT NULL,
  `TBLA_COAC_STAT` char(1) DEFAULT NULL,
  `TBLA_ENTR_DATE` date DEFAULT NULL,
  `TBLA_ENTR_TIME` time DEFAULT NULL,
  `TBLA_ENTR_USER` varchar(5) DEFAULT NULL,
  `TBLA_UPDT_DATE` date DEFAULT NULL,
  `TBLA_UPDT_TIME` time DEFAULT NULL,
  `TBLA_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`TBLA_COAC_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.tblapoli
CREATE TABLE IF NOT EXISTS `tblapoli` (
  `TBLA_POLI_CODE` char(2) NOT NULL,
  `TBLA_POLI_NAME` varchar(50) DEFAULT NULL,
  `TBLA_POLI_STAT` char(1) DEFAULT NULL,
  `TBLA_ENTR_DATE` date DEFAULT NULL,
  `TBLA_ENTR_TIME` time DEFAULT NULL,
  `TBLA_ENTR_USER` varchar(5) DEFAULT NULL,
  `TBLA_UPDT_DATE` date DEFAULT NULL,
  `TBLA_UPDT_TIME` time DEFAULT NULL,
  `TBLa_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`TBLA_POLI_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.tblebank
CREATE TABLE IF NOT EXISTS `tblebank` (
  `TBLE_BANK_CODE` char(3) NOT NULL,
  `TBLE_BANK_NAME` varchar(60) DEFAULT NULL,
  `TBLE_BANK_STAT` char(1) DEFAULT NULL,
  `TBLE_ENTR_DATE` date DEFAULT NULL,
  `TBLE_ENTR_TIME` time DEFAULT NULL,
  `TBLE_ENTR_USER` varchar(5) DEFAULT NULL,
  `TBLE_UPDT_DATE` date DEFAULT NULL,
  `TBLE_UPDT_TIME` time DEFAULT NULL,
  `TBLE_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`TBLE_BANK_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.tbledivi
CREATE TABLE IF NOT EXISTS `tbledivi` (
  `TBLE_DIVI_CODE` char(3) NOT NULL,
  `TBLE_DIVI_NAME` varchar(50) DEFAULT NULL,
  `TBLE_DIVI_STAT` char(1) DEFAULT NULL,
  `TBLE_ENTR_DATE` date DEFAULT NULL,
  `TBLE_ENTR_TIME` time DEFAULT NULL,
  `TBLE_ENTR_USER` varchar(5) DEFAULT NULL,
  `TBLE_UPDT_DATE` date DEFAULT NULL,
  `TBLE_UPDT_TIME` time DEFAULT NULL,
  `TBLE_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`TBLE_DIVI_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.tblepost
CREATE TABLE IF NOT EXISTS `tblepost` (
  `TBLE_POST_CODE` char(3) NOT NULL,
  `TBLE_POST_NAME` varchar(50) DEFAULT NULL,
  `TBLE_POST_STAT` char(1) DEFAULT NULL,
  `TBLE_ENTR_DATE` date DEFAULT NULL,
  `TBLE_ENTR_TIME` time DEFAULT NULL,
  `TBLE_ENTR_USER` varchar(5) DEFAULT NULL,
  `TBLE_UPDT_DATE` date DEFAULT NULL,
  `TBLE_UPDT_TIME` time DEFAULT NULL,
  `TBLE_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`TBLE_POST_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.tblfmedi
CREATE TABLE IF NOT EXISTS `tblfmedi` (
  `TBLF_MEDI_CODE` char(8) NOT NULL,
  `TBLF_MEDI_NAME` varchar(100) DEFAULT NULL,
  `TBLF_MEDI_RATE` decimal(15,2) DEFAULT NULL,
  `TBLF_MEDI_ROOM` char(2) DEFAULT NULL,
  `TBLF_MEDI_TYPE` char(1) DEFAULT NULL,
  `TBLF_MEDI_PAYM` char(1) DEFAULT NULL,
  `TBLF_MEDI_NOTE` varchar(100) DEFAULT NULL,
  `TBLF_MEDI_ACTI` char(1) DEFAULT NULL,
  `TBLF_VIEW_STAT` char(1) DEFAULT NULL,
  `TBLF_ENTR_DATE` date DEFAULT NULL,
  `TBLF_ENTR_TIME` time DEFAULT NULL,
  `TBLF_ENTR_USER` char(5) DEFAULT NULL,
  `TBLF_UPDT_DATE` date DEFAULT NULL,
  `TBLF_UPDT_TIME` time DEFAULT NULL,
  `TBLF_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`TBLF_MEDI_CODE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.tblispec
CREATE TABLE IF NOT EXISTS `tblispec` (
  `TBLI_SPEC_CODE` char(2) NOT NULL,
  `TBLI_SPEC_NAME` varchar(50) DEFAULT NULL,
  `TBLI_SPEC_NOTE` varchar(100) DEFAULT NULL,
  `TBLI_SPEC_STAT` char(1) DEFAULT NULL,
  `TBLI_ENTR_DATE` date DEFAULT NULL,
  `TBLI_ENTR_TIME` time DEFAULT NULL,
  `TBLI_ENTR_USER` varchar(5) DEFAULT NULL,
  `TBLI_UPDT_DATE` date DEFAULT NULL,
  `TBLI_UPDT_TIME` time DEFAULT NULL,
  `TBLI_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`TBLI_SPEC_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.tblitype
CREATE TABLE IF NOT EXISTS `tblitype` (
  `TBLI_TYPE_CODE` char(4) NOT NULL,
  `TBLI_TYPE_NAME` varchar(50) DEFAULT NULL,
  `TBLI_TYPE_CATE` char(2) DEFAULT NULL,
  `TBLI_TYPE_NOTE` varchar(100) DEFAULT NULL,
  `TBLI_TYPE_STAT` char(1) DEFAULT NULL,
  `TBLI_ENTR_DATE` date DEFAULT NULL,
  `TBLI_ENTR_TIME` time DEFAULT NULL,
  `TBLI_ENTR_USER` varchar(5) DEFAULT NULL,
  `TBLI_UPDT_DATE` date DEFAULT NULL,
  `TBLI_UPDT_TIME` time DEFAULT NULL,
  `TBLI_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`TBLI_TYPE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.tbliunit
CREATE TABLE IF NOT EXISTS `tbliunit` (
  `TBLI_UNIT_CODE` char(3) NOT NULL,
  `TBLI_UNIT_NAME` varchar(50) DEFAULT NULL,
  `TBLI_UNIT_DEVI` int DEFAULT NULL,
  `TBLI_UNIT_STAT` char(1) DEFAULT NULL,
  `TBLI_ENTR_DATE` date DEFAULT NULL,
  `TBLI_ENTR_TIME` time DEFAULT NULL,
  `TBLI_ENTR_USER` varchar(5) DEFAULT NULL,
  `TBLI_UPDT_DATE` date DEFAULT NULL,
  `TBLI_UPDT_TIME` time DEFAULT NULL,
  `TBLI_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`TBLI_UNIT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.tblivarn
CREATE TABLE IF NOT EXISTS `tblivarn` (
  `TBLI_VARN_CODE` char(2) NOT NULL,
  `TBLI_VARN_NAME` varchar(50) DEFAULT NULL,
  `TBLI_VARN_NOTE` varchar(100) DEFAULT NULL,
  `TBLI_VARN_STAT` char(1) DEFAULT NULL,
  `TBLI_ENTR_DATE` date DEFAULT NULL,
  `TBLI_ENTR_TIME` time DEFAULT NULL,
  `TBLI_ENTR_USER` varchar(5) DEFAULT NULL,
  `TBLI_UPDT_DATE` date DEFAULT NULL,
  `TBLI_UPDT_TIME` time DEFAULT NULL,
  `TBLI_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`TBLI_VARN_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.tbllexam
CREATE TABLE IF NOT EXISTS `tbllexam` (
  `TBLL_EXAM_CODE` char(2) NOT NULL,
  `TBLL_EXAM_NAME` varchar(50) DEFAULT NULL,
  `TBLL_VIEW_STAT` char(1) DEFAULT NULL,
  `TBLL_ENTR_DATE` date DEFAULT NULL,
  `TBLL_ENTR_TIME` time DEFAULT NULL,
  `TBLL_ENTR_USER` varchar(5) DEFAULT NULL,
  `TBLL_UPDT_DATE` date DEFAULT NULL,
  `TBLL_UPDT_TIME` time DEFAULT NULL,
  `TBLL_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`TBLL_EXAM_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.tbllmanu
CREATE TABLE IF NOT EXISTS `tbllmanu` (
  `TBLL_MANU_CODE` char(2) NOT NULL,
  `TBLL_MANU_NAME` varchar(50) DEFAULT NULL,
  `TBLL_VIEW_STAT` char(1) DEFAULT NULL,
  `TBLL_ENTR_DATE` date DEFAULT NULL,
  `TBLL_ENTR_TIME` time DEFAULT NULL,
  `TBLL_ENTR_USER` varchar(5) DEFAULT NULL,
  `TBLL_UPDT_DATE` date DEFAULT NULL,
  `TBLL_UPDT_TIME` time DEFAULT NULL,
  `TBLL_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`TBLL_MANU_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.tbllunit
CREATE TABLE IF NOT EXISTS `tbllunit` (
  `TBLL_UNIT_CODE` varchar(10) NOT NULL,
  `TBLL_UNIT_NAME` varchar(50) DEFAULT NULL,
  `TBLL_VIEW_STAT` char(1) DEFAULT NULL,
  `TBLL_ENTR_DATE` date DEFAULT NULL,
  `TBLL_ENTR_TIME` time DEFAULT NULL,
  `TBLL_ENTR_USER` varchar(5) DEFAULT NULL,
  `TBLL_UPDT_DATE` date DEFAULT NULL,
  `TBLL_UPDT_TIME` time DEFAULT NULL,
  `TBLL_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`TBLL_UNIT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.tblpsgna
CREATE TABLE IF NOT EXISTS `tblpsgna` (
  `TBLP_SGNA_CODE` char(2) NOT NULL,
  `TBLP_SGNA_NAME` varchar(50) DEFAULT NULL,
  `TBLP_SGNA_USAG` varchar(255) DEFAULT NULL,
  `TBLP_SGNA_STAT` char(1) DEFAULT NULL,
  `TBLP_ENTR_DATE` date DEFAULT NULL,
  `TBLP_ENTR_TIME` time DEFAULT NULL,
  `TBLP_ENTR_USER` varchar(5) DEFAULT NULL,
  `TBLP_UPDT_DATE` date DEFAULT NULL,
  `TBLP_UPDT_TIME` time DEFAULT NULL,
  `TBLP_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`TBLP_SGNA_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxaalle
CREATE TABLE IF NOT EXISTS `trxaalle` (
  `TRXA_PATI_CODE` char(10) NOT NULL,
  `TRXA_ALLE_NOTE` text,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`TRXA_PATI_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxaassm
CREATE TABLE IF NOT EXISTS `trxaassm` (
  `TRXA_ASSM_CODE` char(14) NOT NULL,
  `TRXA_MEDI_ALLE` char(1) DEFAULT NULL,
  `TRXA_FOOD_ALLE` char(1) DEFAULT NULL,
  `TRXA_CHRO_DSSE` char(1) DEFAULT NULL,
  `TRXA_OTHR_DSSE` char(1) DEFAULT NULL,
  `TRXA_PATI_CARE` char(1) DEFAULT NULL,
  `TRXA_PATI_SURGE` char(1) DEFAULT NULL,
  `TRXA_PATI_SMOKE` char(1) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`TRXA_ASSM_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxacsbl
CREATE TABLE IF NOT EXISTS `trxacsbl` (
  `TRXA_CSBL_CODE` char(14) DEFAULT NULL,
  `TRXA_CSBL_DOCT` char(5) DEFAULT NULL,
  `TRXA_STOCK_CODE` char(4) DEFAULT NULL,
  `TRXA_STOCK_PRIC` decimal(15,2) DEFAULT NULL,
  `TRXA_STOCK_QUTY` int DEFAULT NULL,
  `TRXA_MEDI_ROOM` char(2) DEFAULT NULL,
  `TRXA_CSBL_STAT` char(1) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxacust
CREATE TABLE IF NOT EXISTS `trxacust` (
  `TRXA_LIST_CODE` char(7) NOT NULL,
  `TRXA_INVE_CODE` char(4) DEFAULT NULL,
  `TRXA_CUST_CODE` char(7) DEFAULT NULL,
  `TRXA_CUST_TYPE` char(1) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`TRXA_LIST_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxadiag
CREATE TABLE IF NOT EXISTS `trxadiag` (
  `TRXA_EXAM_CODE` char(14) DEFAULT NULL,
  `TRXA_DIAG_CODE` varchar(6) DEFAULT NULL,
  `TRXA_DIAG_NAME` varchar(200) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  KEY `TRXA_EXAM_CODE` (`TRXA_EXAM_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxadrug
CREATE TABLE IF NOT EXISTS `trxadrug` (
  `TRXA_DRUG_CODE` char(14) NOT NULL,
  `TRXA_PAYM_AMNT` decimal(15,2) DEFAULT NULL,
  `TRXA_PAYM_DISC` decimal(15,2) DEFAULT NULL,
  `TRXA_PAYM_OUTS` decimal(15,2) DEFAULT NULL,
  `TRXA_PAYM_MODE` char(3) DEFAULT NULL,
  `TRXA_DRUG_STAT` char(1) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`TRXA_DRUG_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxaexam
CREATE TABLE IF NOT EXISTS `trxaexam` (
  `TRXA_EXAM_CODE` char(14) NOT NULL,
  `TRXA_EXAM_DOCT` char(5) DEFAULT NULL,
  `TRXA_EXAM_HGHT` varchar(50) DEFAULT NULL,
  `TRXA_EXAM_WGHT` varchar(50) DEFAULT NULL,
  `TRXA_EXAM_WAIST` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `TRXA_EXAM_BMI` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `TRXA_EXAM_BLOD` varchar(50) DEFAULT NULL,
  `TRXA_EXAM_TEMP` varchar(50) DEFAULT NULL,
  `TRXA_EXAM_RR` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `TRXA_EXAM_HR` varchar(10) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `TRXA_EXAM_COMP` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `TRXA_EXAM_ANAM` text,
  `TRXA_EXAM_BODY` text,
  `TRXA_EXAM_DIAG` varchar(200) DEFAULT NULL,
  `TRXA_EXAM_PRSC` text,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`TRXA_EXAM_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxaexec
CREATE TABLE IF NOT EXISTS `trxaexec` (
  `TRXA_EXEC_CODE` char(7) NOT NULL,
  `TRXA_EXEC_DATE` date DEFAULT NULL,
  `TRXA_REQU_CODE` char(7) DEFAULT NULL,
  `TRXA_ESTM_DATE` date DEFAULT NULL,
  `TRXA_TRAN_DATE` date DEFAULT NULL,
  `TRXA_RCVE_DATE` date DEFAULT NULL,
  `TRXA_WARE_FROM` char(4) DEFAULT NULL,
  `TRXA_WARE_DEST` char(4) DEFAULT NULL,
  `TRXA_EXEC_NOTE` varchar(100) DEFAULT NULL,
  `TRXA_EXEC_STAT` char(1) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`TRXA_EXEC_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxainvc
CREATE TABLE IF NOT EXISTS `trxainvc` (
  `TRXA_INVC_CODE` varchar(20) NOT NULL,
  `TRXA_INVC_DATE` date DEFAULT NULL,
  `TRXA_PROC_CODE` char(7) DEFAULT NULL,
  `TRXA_DUED_DATE` date DEFAULT NULL,
  `TRXA_SUPL_CODE` char(7) DEFAULT NULL,
  `TRXA_INVC_STAT` char(1) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`TRXA_INVC_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxajrnl
CREATE TABLE IF NOT EXISTS `trxajrnl` (
  `TRXA_JRNL_CODE` char(7) DEFAULT NULL,
  `TRXA_JRNL_DATE` date DEFAULT NULL,
  `TRXA_COAC_CODE` char(13) DEFAULT NULL,
  `TRXA_COAC_NAME` varchar(50) DEFAULT NULL,
  `TRXA_JRNL_DEBT` decimal(15,2) DEFAULT NULL,
  `TRXA_JRNL_CRDT` decimal(15,2) DEFAULT NULL,
  `TRXA_DIVI_CODE` char(3) DEFAULT NULL,
  `TRXA_DIVI_NAME` varchar(50) DEFAULT NULL,
  `TRXA_JRNL_NOTE` varchar(200) DEFAULT NULL,
  `TRXA_JRNL_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxalabo
CREATE TABLE IF NOT EXISTS `trxalabo` (
  `TRXA_LABO_REGI` char(14) DEFAULT NULL,
  `TRXA_LABO_DOCT` char(5) DEFAULT NULL,
  `TRXA_MAST_CODE` char(7) DEFAULT NULL,
  `TRXA_LABO_RSLT` varchar(10) DEFAULT NULL,
  `TRXA_LABO_NOTE` varchar(200) DEFAULT NULL,
  `TRXA_LABO_STAT` char(1) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` varchar(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` varchar(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxaopna
CREATE TABLE IF NOT EXISTS `trxaopna` (
  `TRXA_OPNA_CODE` char(7) NOT NULL,
  `TRXA_OPNA_DATE` date DEFAULT NULL,
  `TRXA_WARE_CODE` char(4) DEFAULT NULL,
  `TRXA_OPNA_DLAY` varchar(100) DEFAULT NULL,
  `TRXA_FINS_DATE` date DEFAULT NULL,
  `TRXA_OPNA_NOTE` varchar(100) DEFAULT NULL,
  `TRXA_EMPL_CODE` char(10) DEFAULT NULL,
  `TRXA_OPNA_STAT` char(1) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`TRXA_OPNA_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxapaym
CREATE TABLE IF NOT EXISTS `trxapaym` (
  `TRXA_PAYM_CODE` char(7) NOT NULL,
  `TRXA_PAYM_DATE` date DEFAULT NULL,
  `TRXA_COAC_CODE` char(13) DEFAULT NULL,
  `TRXA_CHEQ_CODE` varchar(10) DEFAULT NULL,
  `TRXA_DIVI_CODE` char(3) DEFAULT NULL,
  `TRXA_PAYE_CODE` char(13) DEFAULT NULL,
  `TRXA_PAYM_AMNT` decimal(15,2) DEFAULT NULL,
  `TRXA_PAYM_NOTE` varchar(100) DEFAULT NULL,
  `TRXA_PAYM_STAT` char(1) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`TRXA_PAYM_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxaproc
CREATE TABLE IF NOT EXISTS `trxaproc` (
  `TRXA_PROC_CODE` char(7) NOT NULL,
  `TRXA_PROC_DATE` date DEFAULT NULL,
  `TRXA_PROC_DUED` date DEFAULT NULL,
  `TRXA_PROC_DIVI` char(3) DEFAULT NULL,
  `TRXA_PROC_STAT` char(2) DEFAULT NULL,
  `TRXA_SUPL_CODE` char(7) DEFAULT NULL,
  `TRXA_PROC_FROB` char(1) DEFAULT NULL,
  `TRXA_PROC_VATX` char(1) DEFAULT NULL,
  `TRXA_PROC_TYPE` char(3) DEFAULT NULL,
  `TRXA_TERM_PAID` char(3) DEFAULT NULL,
  `TRXA_DOWN_PAID` decimal(15,2) DEFAULT NULL,
  `TRXA_REMA_PAID` decimal(15,2) DEFAULT NULL,
  `TRXA_PROC_TERM` int DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`TRXA_PROC_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxaprsc
CREATE TABLE IF NOT EXISTS `trxaprsc` (
  `TRXA_PRSC_CODE` char(14) DEFAULT NULL,
  `TRXA_PRSC_DOCT` char(5) DEFAULT NULL,
  `TRXA_STOCK_CODE` char(4) DEFAULT NULL,
  `TRXA_STOCK_BTCH` varchar(10) DEFAULT NULL,
  `TRXA_PRSC_CONC` char(1) DEFAULT NULL,
  `TRXA_STOCK_PRIC` decimal(15,2) DEFAULT NULL,
  `TRXA_STOCK_QUTY` int DEFAULT NULL,
  `TRXA_PRSC_SGNA` char(2) DEFAULT NULL,
  `TRXA_PRSC_USAG` varchar(100) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `TRXA_MEDI_ROOM` char(2) DEFAULT NULL,
  `TRXA_PRSC_STAT` char(1) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  `TRXA_RACIK_ID` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxaracik_head
CREATE TABLE IF NOT EXISTS `trxaracik_head` (
  `TRXAR_ID` int NOT NULL AUTO_INCREMENT,
  `TRXAR_CODE` varchar(14) COLLATE utf8mb4_unicode_ci NOT NULL,
  `TRXAR_NAMA` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `TRXAR_SGNA` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `TRXAR_USAG` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TRXAR_QTY` int NOT NULL DEFAULT '1',
  `TRXAR_VIEW_STAT` char(1) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Y',
  `TRXAR_ENTR_DATE` date DEFAULT NULL,
  `TRXAR_ENTR_TIME` time DEFAULT NULL,
  `TRXAR_ENTR_USER` varchar(5) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`TRXAR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxaregi
CREATE TABLE IF NOT EXISTS `trxaregi` (
  `TRXA_REGI_CODE` char(14) NOT NULL,
  `TRXA_PATI_CODE` char(10) DEFAULT NULL,
  `TRXA_REGI_DATE` date DEFAULT NULL,
  `TRXA_REGI_LIST` char(3) DEFAULT NULL,
  `TRXA_REGI_FROM` char(1) DEFAULT NULL,
  `TRXA_REGI_PAYM` char(1) DEFAULT NULL,
  `TRXA_REGI_DOCT` char(5) DEFAULT NULL,
  `TRXA_REGI_POLI` char(2) DEFAULT NULL,
  `TRXA_REGI_FEE` char(1) DEFAULT NULL,
  `TRXA_REGI_STAT` char(1) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  `TRXA_REGI_RUJUK_TYPE` varchar(20) DEFAULT NULL,
  `TRXA_REGI_RUJUK_NOTE` text,
  PRIMARY KEY (`TRXA_REGI_CODE`),
  KEY `TRXA_ENTR_DATE_TRXA_ENTR_TIME` (`TRXA_ENTR_DATE`,`TRXA_ENTR_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxarequ
CREATE TABLE IF NOT EXISTS `trxarequ` (
  `TRXA_REQU_CODE` char(7) NOT NULL,
  `TRXA_REQU_DATE` date DEFAULT NULL,
  `TRXA_TRAN_DATE` date DEFAULT NULL,
  `TRXA_RCVE_DATE` date DEFAULT NULL,
  `TRXA_WARE_FROM` char(4) DEFAULT NULL,
  `TRXA_WARE_DEST` char(4) DEFAULT NULL,
  `TRXA_TRAN_TYPE` char(1) DEFAULT NULL,
  `TRXA_TRAN_VHCH` char(8) DEFAULT NULL,
  `TRXA_REQU_STAT` char(1) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`TRXA_REQU_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxaretu
CREATE TABLE IF NOT EXISTS `trxaretu` (
  `TRXA_RETU_CODE` char(11) NOT NULL,
  `TRXA_RETU_DATE` date DEFAULT NULL,
  `TRXA_PROC_CODE` char(7) DEFAULT NULL,
  `TRXA_RETU_DIVI` char(3) DEFAULT NULL,
  `TRXA_SUPL_CODE` char(7) DEFAULT NULL,
  `TRXA_RETU_NOTE` varchar(50) DEFAULT NULL,
  `TRXA_RETU_STAT` char(1) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`TRXA_RETU_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxasale
CREATE TABLE IF NOT EXISTS `trxasale` (
  `TRXA_SALE_CODE` char(14) NOT NULL,
  `TRXA_REGI_CODE` char(14) DEFAULT NULL,
  `TRXA_PATI_CODE` char(10) DEFAULT NULL,
  `TRXA_REGI_DOCT` char(5) DEFAULT NULL,
  `TRXA_REGI_POLI` char(2) DEFAULT NULL,
  `TRXA_PAYM_TOTA` decimal(15,2) DEFAULT NULL,
  `TRXA_PAYM_AMNT` decimal(15,2) DEFAULT NULL,
  `TRXA_PAYM_DISC` decimal(15,2) DEFAULT NULL,
  `TRXA_PAYM_OUTS` decimal(15,2) DEFAULT NULL,
  `TRXA_PAYM_MODE` char(6) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`TRXA_SALE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxaschd
CREATE TABLE IF NOT EXISTS `trxaschd` (
  `TRXA_DOCT_USER` char(5) DEFAULT NULL,
  `TRXA_DOCT_NAME` varchar(100) DEFAULT NULL,
  `TRXA_MEDI_ROOM` char(2) DEFAULT NULL,
  `TRXA_SCHD_DAYS` char(1) DEFAULT NULL,
  `TRXA_SCHD_START` time DEFAULT NULL,
  `TRXA_SCHD_END` time DEFAULT NULL,
  `TRXA_SCHD_NOTE` varchar(100) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxatret
CREATE TABLE IF NOT EXISTS `trxatret` (
  `TRXA_TRET_CODE` char(14) DEFAULT NULL,
  `TRXA_TRET_DOCT` char(5) DEFAULT NULL,
  `TRXA_MEDI_CODE` char(8) DEFAULT NULL,
  `TRXA_MEDI_RATE` decimal(15,2) DEFAULT NULL,
  `TRXA_TRET_QUTY` int DEFAULT NULL,
  `TRXA_MEDI_ROOM` char(2) DEFAULT NULL,
  `TRXA_TRET_STAT` char(1) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.trxavend
CREATE TABLE IF NOT EXISTS `trxavend` (
  `TRXA_VEND_CODE` char(7) NOT NULL,
  `TRXA_VEND_DATE` date DEFAULT NULL,
  `TRXA_PROC_CODE` char(7) DEFAULT NULL,
  `TRXA_PROC_DIVI` char(3) DEFAULT NULL,
  `TRXA_SUPL_CODE` char(7) DEFAULT NULL,
  `TRXA_PROC_VATX` char(1) DEFAULT NULL,
  `TRXA_DOWN_PAID` decimal(15,2) DEFAULT NULL,
  `TRXA_REMA_PAID` decimal(15,2) DEFAULT NULL,
  `TRXA_INVC_CODE` varchar(20) DEFAULT NULL,
  `TRXA_DUED_DATE` date DEFAULT NULL,
  `TRXA_VEND_STAT` char(1) DEFAULT NULL,
  `TRXA_VIEW_STAT` char(1) DEFAULT NULL,
  `TRXA_ENTR_DATE` date DEFAULT NULL,
  `TRXA_ENTR_TIME` time DEFAULT NULL,
  `TRXA_ENTR_USER` char(5) DEFAULT NULL,
  `TRXA_UPDT_DATE` date DEFAULT NULL,
  `TRXA_UPDT_TIME` time DEFAULT NULL,
  `TRXA_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`TRXA_VEND_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.vstmast
CREATE TABLE IF NOT EXISTS `vstmast` (
  `VST_MAST_CODE` char(8) NOT NULL,
  `VST_MAST_ROOM` char(2) DEFAULT NULL,
  `VST_MAST_PAYM` char(1) DEFAULT NULL,
  `VST_MAST_USER` char(5) DEFAULT NULL,
  `VST_MAXI_AMNT` int DEFAULT NULL,
  `VST_NOMI_AMNT` decimal(15,2) DEFAULT NULL,
  `VST_VIEW_STAT` char(1) DEFAULT NULL,
  `VST_ENTR_DATE` date DEFAULT NULL,
  `VST_ENTR_TIME` time DEFAULT NULL,
  `VST_ENTR_USER` char(5) DEFAULT NULL,
  `VST_UPDT_DATE` date DEFAULT NULL,
  `VST_UPDT_TIME` time DEFAULT NULL,
  `VST_UPDT_USER` char(5) DEFAULT NULL,
  PRIMARY KEY (`VST_MAST_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

-- Dumping structure for table siskadb.waremast
CREATE TABLE IF NOT EXISTS `waremast` (
  `WARE_HOUS_CODE` char(4) NOT NULL,
  `WARE_HOUS_NAME` varchar(50) DEFAULT NULL,
  `WARE_HOUS_LOCA` char(4) DEFAULT NULL,
  `WARE_MEDI_ROOM` char(2) DEFAULT NULL,
  `WARE_HOUS_TYPE` char(1) DEFAULT NULL,
  `WARE_EMPL_CODE` char(10) DEFAULT NULL,
  `WARE_HOUS_NOTE` varchar(100) DEFAULT NULL,
  `WARE_HOUS_STAT` char(1) DEFAULT NULL,
  `WARE_ENTR_DATE` date DEFAULT NULL,
  `WARE_ENTR_TIME` time DEFAULT NULL,
  `WARE_ENTR_USER` varchar(5) DEFAULT NULL,
  `WARE_UPDT_DATE` date DEFAULT NULL,
  `WARE_UPDT_TIME` time DEFAULT NULL,
  `WARE_UPDT_USER` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`WARE_HOUS_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Data exporting was unselected.

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
